name: linux_clang++_x86_32

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x86
    - uses: actions/checkout@v2
    - name: build
      run: c++ -m32 -o prog prog.cpp -std=c++17 > build_log.txt 2>&1
      continue-on-error: true
    - uses: actions/upload-artifact@v2
      with:
        name: build_log.txt
        path: build_log.txt
    - uses: actions/upload-artifact@v2
      with:
        name: prog
        path: prog
    - name: Check binary file
      run: ls -alh prog; file prog
    - name: Run executable prog and collect output
      run: ./prog > output.txt 2>&1
      continue-on-error: true
    - uses: actions/upload-artifact@v2
      with:
        name: output.txt
        path: output.txt
    - name: compare expected output
      run: cmp output.txt expected_output.txt
