name: linux_g++_aarch64

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Install cross-compiler, as well as Qemu CPU emulator
      run: sudo apt update; sudo apt install -y g++-aarch64-linux-gnu qemu-user-static
    - uses: actions/checkout@v2
    - name: build
      run: aarch64-linux-gnu-g++ -o prog nrvo_test.cpp -std=c++17 -static-libgcc -static-libstdc++ -Wl,-rpath,lib/aarch64/ > build_log.txt 2>&1
    - uses: actions/upload-artifact@v2
      with:
        name: build_log.txt
        path: build_log.txt
    - name: Check binary file
      run: ls -alh prog; file prog
    - name: Instate interpretter for aarch64 (otherwise 'prog' won't run)
      run: sudo cp lib/aarch64/ld-linux-aarch64.so.1 /lib
    - name: Run executable prog and collect output
      run: ./prog > output.txt 2>&1
      continue-on-error: true
    - uses: actions/upload-artifact@v2
      with:
        name: output.txt
        path: output.txt
    - name: compare expected output
      run: cmp output.txt expected_output.txt
