name: linux_g++_sparc64

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Install the Qemu CPU emulator
      run: sudo apt update; sudo apt install -y qemu-user-static
    - uses: actions/checkout@v4
    - name: Install Sparc64 ccross-compiler from Debian packages
      run: cd compilers/sparc64 && sudo ./install_sparc64_compiler.sh
    - name: Install version 2.36 of glibc
      run: cd compilers/sparc64 && sudo dpkg --auto-deconfigure -i ./locales*.deb ./libc6_2.36-0ubuntu4_amd64.deb
    - name: build
      run: /usr/bin/sparc64-linux-gnu-g++-13 -o prog nrvo_test.cpp -std=c++17 -static > build_log.txt 2>&1
      continue-on-error: true
    - uses: actions/upload-artifact@v4
      with:
        name: build_log.txt
        path: build_log.txt
    - name: Check binary file
      run: ls -alh prog; file prog
    - name: Run executable prog and collect output
      run: qemu-sparc64-static ./prog > output.txt 2>&1
    - uses: actions/upload-artifact@v4
      with:
        name: output.txt
        path: output.txt
    - name: compare expected output
      run: cmp output.txt expected_output.txt
