name: linux_g++_mips64

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Install cross-compiler, as well as Qemu CPU emulator
      run: sudo apt update; sudo apt install -y g++-mips64-linux-gnuabi64 qemu-user-static
    - uses: actions/checkout@v4
    - name: build
      run: mips64-linux-gnuabi64-g++ -o prog nrvo_test.cpp -std=c++17 -static > build_log.txt 2>&1
    - uses: actions/upload-artifact@v4
      with:
        name: build_log.txt
        path: build_log.txt
    - name: Check binary file
      run: ls -alh prog; file prog
    - name: Run executable prog and collect output
      run: ./prog > output.txt 2>&1
      continue-on-error: true
    - uses: actions/upload-artifact@v4
      with:
        name: output.txt
        path: output.txt
    - name: compare expected output
      run: cmp output.txt expected_output.txt
