name: mswin_msvc_x86_64

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    name: run on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1.4.1
      with:
        arch: x64
    - name: build
      run: cl /machine:x64 /Fe:prog.exe nrvo_test.cpp /std:c++17 /EHsc
      shell: cmd
    - name: upload executable
      uses: actions/upload-artifact@v2
      with:
        name: prog.exe
        path: prog.exe
    - name: Run executable prog and collect output
      run: prog.exe > output.txt
      shell: cmd
    - uses: actions/upload-artifact@v2
      with:
        name: output.txt
        path: output.txt
    - name: compare expected output
      run:  compilers\dos2unix.exe output.txt && fc output.txt expected_output.txt
      shell: cmd
