name: mswin_clang++_x86_64

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    name: run on windows
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: build
      run: clang++ -o prog.exe nrvo_test.cpp -std=c++17
      shell: cmd
    - name: upload executable
      uses: actions/upload-artifact@v4
      with:
        name: prog.exe
        path: prog.exe
    - name: Run executable prog and collect output
      run: prog.exe > output.txt
      shell: cmd
    - uses: actions/upload-artifact@v4
      with:
        name: output.txt
        path: output.txt
    - name: compare expected output
      run:  compilers\dos2unix.exe output.txt && fc output.txt expected_output.txt
      shell: cmd
